config/routes.rb
Rails.application.routes.draw do
  
  get 'voting', to: 'voting#edit'
  match 'voting' => 'voting#update', :via => [:patch]
  
  resources :reasons

  devise_for :users

  resources :constituencies

  resources :provinces

  resources :committees
  
  get '/report', to: 'report/base#index'
  namespace :report do
    resources :provinces
    resources :constituencies
  end
  

  root 'welcome#index'

end

app/models/constituency.rb
class Constituency < ActiveRecord::Base
  belongs_to :province
  has_one :user
  has_many :committees, through: :province
  has_many :valid_votes
  has_many :invalid_votes
  accepts_nested_attributes_for :valid_votes
  accepts_nested_attributes_for :invalid_votes #, allow_destroy: true, reject_if: proc { |invalid_vote| invalid_vote[:name].blank? }
  validates_uniqueness_of :number, :scope => :province_id
end

app/controllers/constituencies_controller.rb
class ConstituenciesController < ApplicationController
  before_filter :verify_admin  
  before_action :authenticate_user!   
  before_action :set_constituency, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /constituencies
  # GET /constituencies.json
  def index
    @constituencies = Constituency.all
  end

  # GET /constituencies/1
  # GET /constituencies/1.json
  def show
  end

  # GET /constituencies/new
  def new
    @constituency = Constituency.new
  end

  # GET /constituencies/1/edit
  def edit
  end

  # POST /constituencies
  # POST /constituencies.json
  def create
    @constituency = Constituency.new(constituency_params)

    respond_to do |format|
      if @constituency.save
        format.html { redirect_to @constituency, notice: 'Constituency was successfully created.' }
        format.json { render :show, status: :created, location: @constituency }
      else
        format.html { render :new }
        format.json { render json: @constituency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /constituencies/1
  # PATCH/PUT /constituencies/1.json
  def update
    respond_to do |format|
      if @constituency.update(constituency_params_update)
        format.html { redirect_to @constituency, notice: 'Constituency was successfully updated.' }
        format.json { render :show, status: :ok, location: @constituency }
      else
        format.html { render :edit }
        format.json { render json: @constituency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /constituencies/1
  # DELETE /constituencies/1.json
  def destroy
    @constituency.destroy
    respond_to do |format|
      format.html { redirect_to constituencies_url, notice: 'Constituency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def verify_admin
      redirect_to root_url unless current_user.role == "admin"
    end  
  
    # Use callbacks to share common setup or constraints between actions.
    def set_constituency
      @constituency = Constituency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def constituency_params
      params.require(:constituency).permit(:number, :mandates, :voters, :province_id)
    end  
    def constituency_params_update
      params.require(:constituency).permit(:mandates, :voters)
    end  
end

app/controllers/report/constituencies_controller.rb
module Report
  class ConstituenciesController < BaseController 
    before_action :set_constituency, only: [:show]
    load_and_authorize_resource 

    def show
    end  

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_constituency
        @constituency = Constituency.find(params[:id])
        @valid_votes_sum = @constituency.valid_votes.sum('quantity')
        @invalid_votes_sum = @constituency.invalid_votes.sum('quantity')
      end
    end
    
end

app/helpers/constituencies_helper.rb
module ConstituenciesHelper
end

app/views/constituencies/_form.html.erb
<%= form_for @constituency, :html => {:class => "form-horizontal"} do |f| %>

  <%= render 'layouts/errors', object: @constituency %>

<div class="col-sm-6">
  <% if action_name != 'edit' %>
  <div class="form-group">
    <%= f.label :province_id, class: "control-label col-sm-4" %>
    <div class="col-sm-4">
	<%= f.collection_select(:province_id, Province.all, :id, :name, {}, {:class => 'form-control col-sm-4', :required => true}) %>	      
    </div>    
  </div>  
  
  <div class="form-group">
      <%= f.label :number, class: "control-label col-sm-4" %>
    <div class="col-sm-4">
      <%= f.number_field :number, class: "form-control", :required => true %>      
    </div>
  </div>
  <% end %>

  <div class="form-group">
      <%= f.label :mandates, class: "control-label col-sm-4" %>
    <div class="col-sm-4">
      <%= f.number_field :mandates, class: "form-control" %>      
    </div>
  </div>


  <div class="form-group">
      <%= f.label :voters, class: "control-label col-sm-4" %>
    <div class="col-sm-4">
      <%= f.number_field :voters, class: "form-control" %>      
    </div>
  </div>

 <div class="form-group action">
  <div class="col-sm-4 control-label">
    <%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> powrót'.html_safe, constituencies_path, class: "btn btn-sm btn-primary" %>
  </div>
  <div class="col-sm-4">
    <%= f.submit 'zapisz okręg', class: "btn btn-default form-control" %>
  </div>
 </div>
</div>  
<% end %>

app/views/constituencies/edit.html.erb
<div class="page-header">
  <h1>Okręg nr <%= @constituency.number %>, <%= @constituency.province.name %></h1>  
</div>


<%= render 'form' %>

app/views/constituencies/index.html.erb
<div class="page-header">
  <h1>Okręgi</h1>
</div>

<div class="col-lg-offset-11">
  &nbsp; <%= link_to '<span class="glyphicon glyphicon-plus"></span> dodaj'.html_safe, new_constituency_path, class: "btn btn-success btn-xs" %>
</div>

<div class="bs-component">
  <table class="table table-striped table-hover ">
    <thead>
      <tr>
        <th>Województwo</th>        
        <th>Numer</th>
        <th>Ilość mandatów</th>
        <th>Ilość uprawnionych do głosowania</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @constituencies.each do |constituency| %>
        <tr>
          <td><% if constituency.province.present? %><%= constituency.province.name %><% end %></td>          
          <td><%= constituency.number %></td>
          <td><%= constituency.mandates %></td>
          <td><%= constituency.voters %></td>
          <td class="col-md-1"><a href="<%= url_for :action => 'show', :id => constituency.id %>" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-eye-open"></span> pokaż</a></td>
          <td class="col-md-1"><a href="<%= edit_constituency_path(constituency) %>" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-pencil"></span>  edytuj</a></td>
          <td class="col-md-1"><%= link_to '<span class="glyphicon glyphicon-remove"></span> usuń'.html_safe, constituency, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

app/views/constituencies/new.html.erb
<div class="page-header">
  <h1>Nowy Okręg</h1>  
</div>

<%= render 'form' %>

app/views/constituencies/show.html.erb
<div class="page-header">
  <h1>Okręg nr <%= @constituency.number %>, <%= @constituency.province.name %></h1>  
</div>

<div class="col-lg-12" style="padding-bottom: 10px;">

  <div class="col-lg-3 text-right"><b>Ilość mandatów:</b></div>
  <div class="col-lg-9"><%= @constituency.mandates %></div>
  
</div>

<div class="col-lg-12" style="padding-bottom: 25px;">

  <div class="col-lg-3 text-right"><b>Ilość uprawnionych do głosowania:</b></div>
  <div class="col-lg-9"><%= @constituency.voters %></div>

</div>

  <div class="col-sm-4 control-label">
    <%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> powrót'.html_safe, constituencies_path, class: "btn btn-sm btn-primary" %>
  </div>