config/routes.rb
Rails.application.routes.draw do
  
  get 'voting', to: 'voting#edit'
  match 'voting' => 'voting#update', :via => [:patch]
  
  resources :reasons

  devise_for :users

  resources :constituencies

  resources :provinces

  resources :committees
  
  get '/report', to: 'report/base#index'
  namespace :report do
    resources :provinces
    resources :constituencies
  end
  

  root 'welcome#index'

end

app/models/committee.rb
class Committee < ActiveRecord::Base
  has_and_belongs_to_many :provinces
#  has_many :constituencies, through: :provinces
  has_many :valid_votes#, through: :constituencies
  validates_uniqueness_of :name
end

app/controllers/committees_controller.rb
class CommitteesController < ApplicationController
  before_action :authenticate_user!   
  before_action :set_committee, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /committees
  # GET /committees.json
  def index
    @committees = Committee.all
  end

  # GET /committees/1
  # GET /committees/1.json
  def show
    @provinces = @committee.provinces
  end

  # GET /committees/new
  def new
    @committee = Committee.new
  end

  # GET /committees/1/edit
  def edit
  end

  # POST /committees
  # POST /committees.json
  def create
    @committee = Committee.new(committee_params)

    respond_to do |format|
      if @committee.save
        format.html { redirect_to @committee, notice: 'Committee was successfully created.' }
        format.json { render :show, status: :created, location: @committee }
      else
        format.html { render :new }
        format.json { render json: @committee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /committees/1
  # PATCH/PUT /committees/1.json
  def update
    respond_to do |format|
      if @committee.update(committee_params)
        format.html { redirect_to @committee, notice: 'Committee was successfully updated.' }
        format.json { render :show, status: :ok, location: @committee }
      else
        format.html { render :edit }
        format.json { render json: @committee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /committees/1
  # DELETE /committees/1.json
  def destroy
    @committee.destroy
    respond_to do |format|
      format.html { redirect_to committees_url, notice: 'Committee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_committee
      @committee = Committee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def committee_params
      params.require(:committee).permit(:name, :logo)
    end
end

app/helpers/committees_helper.rb
module CommitteesHelper
end

app/views/committees/_form.html.erb
<%= form_for @committee, :html => {:class => "form-horizontal"} do |f| %>

  <%= render 'layouts/errors', object: @committee %>

<div class="col-sm-6">
  <div class="form-group">
      <%= f.label :name, class: "control-label col-sm-4" %>
    <div class="col-sm-6">
      <%= f.text_field :name, class: "form-control", :required => true %>      
    </div>
  </div>

  <%#*<div class="field">%>
    <%#= f.label :logo %><br>
    <%#= f.text_field :logo %>
  <%#*</div>%>
    
 <div class="form-group action">
  <div class="col-sm-4 control-label">
    <%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> powrót'.html_safe, committees_path, class: "btn btn-sm btn-primary" %>
  </div>
  <div class="col-sm-4">
    <%= f.submit 'zapisz komitet', class: "btn btn-default form-control" %>
  </div>
 </div>
  
</div>  
<% end %>

app/views/committees/edit.html.erb
<div class="page-header">
  <h1>Edycja komitetu</h1>
</div>

<%= render 'form' %>

app/views/committees/index.html.erb
<div class="page-header">
<h1>Komitety</h1>
</div>

<div class="col-lg-offset-11">
  &nbsp; <%= link_to '<span class="glyphicon glyphicon-plus"></span> dodaj'.html_safe, new_committee_path, class: "btn btn-success btn-xs" %>
</div>


<div class="bs-component">
  <table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Nazwa</th>
      <th>Logo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @committees.each do |committee| %>
      <tr>
        <td><%= committee.name %></td>
        <td><%= committee.logo %></td>
        <td class="col-md-1"><a href="<%= url_for :action => 'show', :id => committee.id %>" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-eye-open"></span> pokaż</a></td>
          <td class="col-md-1"><a href="<%= edit_committee_path(committee) %>" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-pencil"></span>  edytuj</a></td>
          <td class="col-md-1"><%= link_to '<span class="glyphicon glyphicon-remove"></span> usuń'.html_safe, committee, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

app/views/committees/new.html.erb
<div class="page-header">
  <h1>Nowy komitet</h1>
</div>

<%= render 'form' %>

app/views/committees/show.html.erb
<% @provinces = @committee.provinces %>
<div class="page-header">
<h1><%= @committee.name %></h1>
</div>

<%#*<p>%>
  <%#*<strong>Logo:</strong>%>
  <%#= @committee.logo %>
<%#*</p>%>

<h2>Województwa</h2>

<%= render :file => '/provinces/_index' %>

  <div class="col-sm-4 control-label">
    <%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> powrót'.html_safe, committees_path, class: "btn btn-sm btn-primary" %>
  </div>