config/routes.rb
Rails.application.routes.draw do
  
  get 'voting', to: 'voting#edit'
  match 'voting' => 'voting#update', :via => [:patch]
  
  resources :reasons

  devise_for :users

  resources :constituencies

  resources :provinces

  resources :committees
  
  get '/report', to: 'report/base#index'
  namespace :report do
    resources :provinces
    resources :constituencies
  end
  

  root 'welcome#index'

end

app/models/province.rb
class Province < ActiveRecord::Base
  has_and_belongs_to_many :committees
  has_many :valid_votes, through: :constituencies
  has_many :invalid_votes, through: :constituencies
  has_many :constituencies
  validates_uniqueness_of :name
end

app/controllers/provinces_controller.rb
class ProvincesController < ApplicationController
  before_action :authenticate_user!  
  before_action :set_province, only: [:show, :edit, :update, :destroy]
  before_action :set_committees
  load_and_authorize_resource
  
  # GET /provinces
  # GET /provinces.json
  def index
  end

  # GET /provinces/1
  # GET /provinces/1.json
  def show
  end

  # GET /provinces/new
  def new
    @province = Province.new
  end

  # GET /provinces/1/edit
  def edit
  end

  # POST /provinces
  # POST /provinces.json
  def create
    @province = Province.new(province_params)
    handle_committees_provinces
    
    respond_to do |format|
      if @province.save
        format.html { redirect_to @province, notice: 'Province was successfully created.' }
        format.json { render :show, status: :created, location: @province }
      else
        format.html { render :new }
        format.json { render json: @province.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /provinces/1
  # PATCH/PUT /provinces/1.json
  def update
    handle_committees_provinces
    
    respond_to do |format|
      if @province.update(province_params)
        format.html { redirect_to @province, notice: 'Province was successfully updated.' }
        format.json { render :show, status: :ok, location: @province }
      else
        format.html { render :edit }
        format.json { render json: @province.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /provinces/1
  # DELETE /provinces/1.json
  def destroy
    @province.destroy
    respond_to do |format|
      format.html { redirect_to provinces_url, notice: 'Province was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def handle_committees_provinces
      if params['committee_ids']
        @province.committees.clear
        committees = params['committee_ids'].map { |id| Committee.find(id) }
        @province.committees << committees
      end
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_province
      @province = Province.find(params[:id])

    end
    
    def set_committees
      @committees = {}	
      Committee.all.collect{|c| @committees[c.name] = c.id}      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def province_params
      params.require(:province).permit(:name)
    end
end

app/controllers/report/provinces_controller.rb
module Report
  class ProvincesController < BaseController  
    before_action :set_province, only: [:show]
    load_and_authorize_resource

    def index
      @provinces = Province.all
      @constituencies = Constituency.all
      @valid_votes = ValidVote.all
      @invalid_votes = InvalidVote.all
      @committees = Committee.all
    end  

    def show
  #    @committees = @province.committees
    end  

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_province
        @province = Province.find(params[:id])
        @valid_votes_sum = @province.valid_votes.sum('quantity')
        @invalid_votes_sum = @province.invalid_votes.sum('quantity')
      end
    end
    
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/helpers/report/provinces_helper.rb
module Report::ProvincesHelper
end

app/views/provinces/_form.html.erb
<%= form_for @province, :html => {:class => "form-horizontal"} do |f| %>

  <%= render 'layouts/errors', object: @province %>

<div class="col-sm-6">
  <div class="form-group">
      <%= f.label :name, class: "control-label col-sm-4" %>
    <div class="col-sm-6">
      <%= f.text_field :name, class: "form-control", :required => true %>      
    </div>
  </div>

  <div class="form-group">
      <%= f.label :committees, class: "control-label col-sm-4" %>
    <div class="col-sm-6" >
      <select id="committee_ids" size="8" class="form-control" name="committee_ids[]" multiple="multiple">
            <%= options_for_select(@committees, @province.committees.collect {|d| d.id }) %>
      </select>    
    </div>
  </div>  
 

 <div class="form-group action">
  <div class="col-sm-4 control-label">
    <%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> powrót'.html_safe, provinces_path, class: "btn btn-sm btn-primary" %>
  </div>
  <div class="col-sm-4">
    <%= f.submit 'zapisz województwo', class: "btn btn-default form-control" %>
  </div>
 </div>
</div>
<% end %>

app/views/provinces/_index.html.erb
<div class="bs-component">
  <table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Nazwa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @provinces.each do |province| %>
      <tr>
        <td><%= province.name %></td>
        <td class="col-md-1"><a href="<%= url_for :controller => 'provinces', :action => 'show', :id => province.id %>" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-eye-open"></span> pokaż</a></td>
        <td class="col-md-1"><a href="<%= edit_province_path(province) %>" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-pencil"></span>  edytuj</a></td>
        <td class="col-md-1"><%= link_to '<span class="glyphicon glyphicon-remove"></span> usuń'.html_safe, province, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/provinces/edit.html.erb
<div class="page-header">
  <h1>Edycja województwa</h1>  
</div>

<%= render 'form' %>

app/views/provinces/index.html.erb
<div class="page-header">
<h1>Województwa</h1>
</div>

<div class="col-lg-offset-11">
  &nbsp; <%= link_to '<span class="glyphicon glyphicon-plus"></span> dodaj'.html_safe, new_province_path, class: "btn btn-success btn-xs" %>
</div>

<%= render 'index' %>

app/views/provinces/new.html.erb
<div class="page-header">
  <h1>Nowe województwo</h1>
</div>

<%= render 'form' %>

app/views/provinces/show.html.erb
<div class="page-header">
<h1>Województwo <%= @province.name %></h1>
</div>

<h3>Komitety</h3>

<div class="bs-component">
  <table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Nazwa</th>
      <th>Logo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @province.committees.each do |committee| %>
      <tr>
        <td><%= committee.name %></td>
        <td><%= committee.logo %></td>
        <td class="col-md-1"><a href="<%= url_for :controller => 'committees', :action => 'show', :id => committee.id %>" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-eye-open"></span> pokaż</a></td>
          <td class="col-md-1"><a href="<%= edit_committee_path(committee) %>" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-pencil"></span>  edytuj</a></td>
          <td class="col-md-1"><%= link_to '<span class="glyphicon glyphicon-remove"></span> usuń'.html_safe, committee, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>


  <div class="col-sm-4 control-label">
    <%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> powrót'.html_safe, provinces_path, class: "btn btn-sm btn-primary" %>
  </div>